# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2300b4d0eade3ba6f5f3206888c46bce51e6384822425373ab475857065cd085bfb1435998af1317fc30d0a58e8dfe34bf544033f18320d172b66b1818fb6551

test:
  secret_key_base: e7c975f5f66410c8d842c8a055191bb6229ecd1fe5313f78ca4887844502f2d6386c97d04cae8ab6d902e43496df0c79416d78e1519f4e48cab29b1e34a12bcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
